chore: prevent main branch from direct commits

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,13 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
+branch="$(git rev-parse --abbrev-ref HEAD)"
+ci=${CI:-"false"}
+
+if [ "$branch" = "main" ] && [ "$ci" = "false" ]; then
+  echo "You can't commit directly to main branch"
+  exit 1
+fi
+
 npx lint-staged
 npm test
